version: "2.0"

services:
  mysql:
    container_name: ${MYSQL_DEV_CONTAINER_NAME}
    image: mysql
    ports:
      - ${MYSQL_DEV_PORT}:3306
    volumes:
      - ${DOCKER_VOLUMNS_PATH}/${MYSQL_DEV_CONTAINER_NAME}:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_DEV_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DEV_SCHEME}
      - MYSQL_USER=${MYSQL_DEV_USER}
      - MYSQL_PASSWORD=${MYSQL_DEV_PASSWORD}
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
